accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('create_profile/', views.create_profile, name='create_profile'),

]

main/urls.py
import django.contrib.auth
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sclad.urls', namespace='sclad')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

sclad/urls.py
from django.urls import path
from . import views


app_name = 'sclad'

urlpatterns = [
    path('', views.index, name='index'),
    path('sclad/', views.dashboard, name='dashboard'),
    path('arrivals/<int:arrival_id>/', views.arrival_detail, name='arrival_detail'),
    path('expenses/create/', views.expense_create, name='expense_create'),
    path('expenses/<int:expense_id>/', views.expense_detail, name='expense_detail'),
    path('products/create/', views.product_create, name='product_create'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('arrivals/create/', views.arrival_create, name='arrival_create'),
    path('suppliers/create/', views.supplier_create, name='supplier_create'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('discounts/create/', views.discount_create, name='discount_create'),
    path('discounts/', views.discount_list, name='discount_list'),
    path('customers/create/', views.customer_create, name='customer_create'),
    path('customers/', views.customer_list, name='customer_list'),
]

sclad/forms.py
from django import forms
from .models import (Product, Arrival, ArrivalComposition, Supplier, Expense,
                     Customer, ExpenseComposition)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['article_number', 'name', 'description', 'purchase_price', 'sell_price',
                  'quantity']


class ArrivalForm(forms.ModelForm):
    class Meta:
        model = Arrival
        fields = ['date', 'supplier', 'description']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'supplier': forms.Select(attrs={'class': 'form-control'}),
        }


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['date', 'customer', 'description']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'customer': forms.Select(attrs={'class': 'form-control'}),
        }


class ExpenseCompositionForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all(), label='Продукт', required=True)
    quantity = forms.IntegerField(min_value=0, initial=0, label='Количество')

    class Meta:
        model = ExpenseComposition
        fields = ['product', 'quantity']


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'

sclad/views.py
import datetime
from decimal import Decimal
from django.forms import inlineformset_factory

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render

from django.contrib.auth.decorators import login_required, user_passes_test

from .forms import ProductForm, ArrivalForm, ExpenseForm, CustomerForm, ExpenseCompositionForm
from .models import Product, Arrival, Expense, Return, Writeoff, Supplier, Customer, ExpenseComposition, \
    ArrivalComposition, Discount
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView

@login_required
def supplier_create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        contact_info = request.POST.get('contact_info')
        Supplier.objects.create(
            name=name,
            contact_info=contact_info,
            user=request.user
        )
        return redirect('sclad:supplier_list')
    return render(request, 'sclad/supplier_create.html')

@login_required
def supplier_list(request):
    suppliers = Supplier.objects.filter(user=request.user)
    return render(request, 'sclad/supplier_list.html', {'suppliers': suppliers})


@login_required
def discount_create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        discount_percentage = request.POST.get('discount_percentage')
        Discount.objects.create(
            name=name,
            description=description,
            discount_percentage=discount_percentage,
            user=request.user
        )
        return redirect('sclad:discount_list')
    return render(request, 'sclad/discount_create.html')

@login_required
def discount_list(request):
    discounts = Discount.objects.filter(user=request.user)
    return render(request, 'sclad/discount_list.html', {'discounts': discounts})


@login_required
def customer_create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        contact_info = request.POST.get('contact_info')
        discount_id = request.POST.get('discount')
        discount = None
        if discount_id:
            discount = Discount.objects.get(id=discount_id, user=request.user)
        customer = Customer.objects.create(
            name=name,
            contact_info=contact_info,
            discount=discount,
            user=request.user
        )
        return redirect('sclad:customer_list')
    discounts = Discount.objects.filter(user=request.user)
    return render(request, 'sclad/customer_create.html', {'discounts': discounts})

@login_required
def customer_list(request):
    customers = Customer.objects.filter(user=request.user)
    return render(request, 'sclad/customer_list.html', {'customers': customers})


def index(request):
    products = Product.objects.all()
    return render(request, 'sclad/index.html', {'products':products})

@login_required
def dashboard(request):
    products = Product.objects.filter(user=request.user).order_by('-id')
    recent_expenses = Expense.objects.filter(user=request.user).order_by('-date', '-id')[:5]
    recent_returns = Return.objects.filter(user=request.user).order_by('-return_date')[:5]
    recent_writeoffs = Writeoff.objects.filter(user=request.user).order_by('-writeoff_date')[:5]
    recent_arrivals = Arrival.objects.filter(user=request.user).order_by('-date','-id')[:5]

    context = {
        'products': products,
        'recent_expenses': recent_expenses,
        'recent_returns': recent_returns,
        'recent_writeoffs': recent_writeoffs,
        'recent_arrivals': recent_arrivals
    }

    return render(request, 'sclad/dashboard.html', context)



# @login_required
# def dashboard(request):
#     user = request.user
#     products = Product.objects.all().order_by('-id')
#
#     if user.role == 'admin':
#         print("ADMIN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
#         # Админ видит все последние продажи, возвраты, списания и прибытия
#         recent_expenses = Expense.objects.order_by('-date', '-id')[:5]
#         recent_returns = Return.objects.order_by('-return_date')[:5]
#         recent_writeoffs = Writeoff.objects.order_by('-writeoff_date')[:5]
#         recent_arrivals = Arrival.objects.order_by('-date','-id')[:5]
#     elif user.role == 'manager':
#         print("MANAGER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
#         # Менеджер видит только свои последние продажи за сегодня
#         today = datetime.date.today()
#         recent_expenses = Expense.objects.filter(store=user.store, date=today).order_by('-date','-id')[:5]
#         recent_returns = []
#         recent_writeoffs = []
#         recent_arrivals = Arrival.objects.order_by('-date','-id')[:5]
#
#     elif user.role == 'employee':
#         print("EMPLOYEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
#         # Менеджер видит только свои последние продажи за сегодня
#         recent_expenses = []
#         recent_returns = []
#         recent_writeoffs = []
#         recent_arrivals = Arrival.objects.filter(store=user.store)[:5]
#
#     else:
#         print("ТУТ НИКОГО НЕ ДОЛЖНО БЫТЬ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
#         # Обычные пользователи не видят информацию о продажах, возвратах и списаниях
#         recent_expenses = []
#         recent_returns = []
#         recent_writeoffs = []
#         recent_arrivals = []
#
#     context = {
#         'products': products,
#         'recent_expenses': recent_expenses,
#         'recent_returns': recent_returns,
#         'recent_writeoffs': recent_writeoffs,
#         'recent_arrivals': recent_arrivals
#     }
#
#     return render(request, 'sclad/dashboard.html', context)

# @login_required
# def dashboard(request):
#     products = Product.objects.all()
#     arrivals = Arrival.objects.all().order_by('-id')
#     expenses = Expense.objects.all().order_by('-id')
#     returns = Return.objects.all().order_by('-id')
#     writeoffs = Writeoff.objects.all().order_by('-id')
#
#     context = {
#         'products': products,
#         'arrivals': arrivals[:5],
#         'expenses': expenses[:5],
#         'returns': returns[:5],
#         'writeoffs': writeoffs[:5],
#     }
#
#     if request.user.role == 'admin':
#         return render(request, 'sclad/dashboard.html', context)
#     elif request.user.role == 'manager':
#         manager_expenses = Expense.objects.filter(user=request.user).order_by('-id')[:5]
#         context['expenses'] = manager_expenses
#         return render(request, 'sclad/dashboard.html', context)
#     else:
#         return render(request, 'sclad/dashboard.html', context)


@login_required
def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            return redirect('sclad:dashboard')
    else:
        form = ProductForm()

    return render(request, 'sclad/product_form.html', {'form': form})


# class ProductDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
#     model = Product
#     template_name = 'sclad/product_detail.html'
#
#     def get_object(self, queryset=None):
#         return get_object_or_404(Product, pk=self.kwargs['pk'])
#
#     def test_func(self):
#         product = self.get_object()
#         return self.request.user.role == 'admin' or product.user == self.request.user


@login_required
def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    context = {
        'product': product,
    }
    return render(request, 'sclad/product_detail.html', context)

# @login_required
# def arrival_create(request):
#     if request.user.role != 'admin':
#         return HttpResponseForbidden("Только администраторы могут создавать приходы.")
#
#     ArrivalCompositionFormSet = inlineformset_factory(
#         Arrival, ArrivalComposition, fields=('product', 'quantity', 'purchase_price'), extra=1, can_delete=False
#     )
#
#     if request.method == 'POST':
#         arrival_form = ArrivalForm(request.POST)
#         arrival_composition_formset = ArrivalCompositionFormSet(request.POST, prefix='composition')
#
#         if arrival_form.is_valid() and arrival_composition_formset.is_valid():
#             arrival = arrival_form.save(commit=False)
#             arrival.user = request.user
#             arrival.save()
#
#             for form in arrival_composition_formset:
#                 arrival_composition = form.save(commit=False)
#                 arrival_composition.arrival = arrival
#                 arrival_composition.user = request.user
#                 arrival_composition.save()
#
#             return redirect('sclad:arrival_detail', arrival_id=arrival.id)
#     else:
#         arrival_form = ArrivalForm()
#         arrival_composition_formset = ArrivalCompositionFormSet(prefix='composition')
#
#     return render(request, 'sclad/arrival_create.html', {
#         'arrival_form': arrival_form,
#         'arrival_composition_formset': arrival_composition_formset
#     })

@login_required
def arrival_create(request):
    if request.method == 'POST':
        supplier_id = request.POST.get('supplier')
        supplier = get_object_or_404(Supplier, id=supplier_id, user=request.user)
        date = request.POST.get('date')
        description = request.POST.get('description')
        arrival = Arrival.objects.create(
            supplier=supplier,
            date=date,
            description=description,
            user=request.user
        )

        for key, value in request.POST.items():
            if key.startswith('product_'):
                product_id = key.split('_')[1]

templates/sclad/arrival_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Создание поступления</h1>
  <form method="post">
    {% csrf_token %}
    <label for="supplier">Поставщик:</label>
    <select name="supplier" id="supplier">
      {% for supplier in suppliers %}
        <option value="{{ supplier.id }}">{{ supplier.name }}</option>
      {% endfor %}
    </select>
    <br>
    <label for="date">Дата:</label>
    <input type="date" name="date" id="date">
    <br>
    <label for="description">Описание:</label>
    <textarea name="description" id="description"></textarea>
    <br>
    <h2>Товары:</h2>
    {% for product in products %}
      <label for="product_{{ product.id }}">{{ product.name }} (в наличии: {{ product.quantity }})</label>
      <input type="number" name="product_{{ product.id }}" id="product_{{ product.id }}" min="0" >
      <br>
    {% endfor %}
    <button type="submit">Создать поступление</button>
  </form>
{% endblock %}

templates/sclad/arrival_detail.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Дата</th>
        <th scope="col">Поставщик</th>
    </tr>
    </thead>
    <tbody>
    <tr>
          <th scope="row">{{ arrival.date }}</th>
          <th scope="row">{{ arrival.supplier }}</th>
    </tr>
    </tbody>
</table>

<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Продукт</th>
        <th scope="col">Количество</th>
        <th scope="col">Цена</th>
        <th scope="col">Сумма</th>
    </tr>
    </thead>
    <tbody>
          {% for item in arrival.arrivalcomposition_set.all %}
          <tr>
                <th scope="row">{{ item.product.name }}</th>
                <th scope="row">{{ item.quantity }}</th>
                <th scope="row">{{ item.purchase_price | floatformat:1}}</th>
               <th scope="row">{{ item.quantity|mul:item.purchase_price|floatformat:2 }}</th>
          </tr>
        {% endfor %}
          <tr bgcolor="cuan">
              <th scope="col">Итого: </th>
              <th scope="row">{{ arrival.total_quant}}</th>
              <th scope="col"></th>
              <th scope="row">${{ arrival.total_arrival_cost|floatformat:2 }}</th>
          </tr>
    </tbody>
</table>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Описание</th>
        <th scope="col">Оформитель</th>
    </tr>
    </thead>
    <tbody>
    <tr>
          <th scope="row">{{ arrival.description }}</th>
          <th scope="row">{{ arrival.user }}</th>
    </tr>
    </tbody>
</table>


{% endblock %}

templates/sclad/arrival_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Создать новое прибытие</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

templates/sclad/customer_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Add Customer</h1>
  <form method="post">
    {% csrf_token %}
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required>
    <label for="contact_info">Contact Info:</label>
    <textarea id="contact_info" name="contact_info" required></textarea>
    <label for="discount">Discount:</label>
    <select id="discount" name="discount">
      <option value="">None</option>
      {% for discount in discounts %}
        <option value="{{ discount.id }}">{{ discount.name }} (\[{{ discount.discount_percentage }}%\])</option>
      {% endfor %}
    </select>
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/sclad/customer_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Customers</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Contact Info</th>
        <th>Discount</th>
      </tr>
    </thead>
    <tbody>
      {% for customer in customers %}
        <tr>
          <td>{{ customer.name }}</td>
          <td>{{ customer.contact_info }}</td>
          <td>
            {% if customer.discount %}
              {{ customer.discount.name }} (\[{{ customer.discount.discount_percentage }}%\])
            {% else %}
              None
            {% endif %}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No customers created yet.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'sclad:customer_create' %}">Add Customer</a>
{% endblock %}

templates/sclad/dashboard.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!
<form action="{% url 'accounts:logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>

  <h2>Dashboard 2024</h2>

  <h3>Номенклатура</h3>

<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Артикул</th>
      <th scope="col">Товар</th>
      <th scope="col">Кол</th>
      <th scope="col">Цена</th>
        <th scope="col">Действия</th>
    </tr>
  </thead>
    <tbody>
      {% for product in products %}
       <tr>
          <th scope="row">{{ product.article_number }}</th>
          <th scope="row" class="text-secondary">{{ product.name }}</th>
          <th scope="row">{{ product.quantity }}</th>
           <th scope="row">${{product.sell_price | floatformat:0}}</th>
           <th scope="row"><a href="{% url 'sclad:product_detail' product.id %}">Просмотреть</a></th>
       </tr>
       {% endfor %}
    </tbody>
  </table>

<a href="{% url 'sclad:product_create' %}" class="btn btn-primary">Добавить продукт</a>
  <h3>Поступления</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Последние поступления</th>
    </tr>
  </thead>
    <tbody>
    {% for arrival in recent_arrivals %}
    <tr>
          <th scope="row"><a href="{% url 'sclad:arrival_detail' arrival.id %}"> {{ arrival }}</a></th>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{% url 'sclad:arrival_create' %}" class="btn btn-primary">Добавить поступление</a>

<h3>Продажи</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Последние продажи</th>
    </tr>
  </thead>
    <tbody>
    {% for expense in recent_expenses %}
    <tr>
          <th scope="row">
              <a href="{% url 'sclad:expense_detail' expense.id %}">
                  {{ expense }}, Сумма: ${{ expense.total_cost}}
              </a>
          </th>
    </tr>
    {% endfor %}
    </tbody>
</table>

<a href="{% url 'sclad:expense_create' %}" class="btn btn-primary">Добавить продажи</a>

<h3>Возвраты</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Последние возвраты</th>
    </tr>
  </thead>
    <tbody>
    {% for return_item in recent_returns %}
    <tr>
          <th scope="row">{{ return_item }}</th>
    </tr>
    {% endfor %}
    </tbody>
</table>

<h3>Cписания</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Последние списания</th>
    </tr>
  </thead>
    <tbody>
    {% for writeoff in recent_writeoffs %}
    <tr>
          <th scope="row">{{ writeoff }}</th>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% else %}
<p>You are not logged in</p>
<a href="{% url 'accounts:login' %}">Log In</a>
{% endif %}


<a href="{% url 'sclad:customer_create' %}" class="btn btn-primary">Добавить покупателя</a>
<a href="{% url 'sclad:discount_create' %}" class="btn btn-primary">Добавить тип скидки</a>

<a href="{% url 'sclad:supplier_create' %}" class="btn btn-primary">Добавить ппотсвавщика</a>
{% endblock %}

templates/sclad/discount_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Discounts</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Discount Percentage</th>
      </tr>
    </thead>
    <tbody>
      {% for discount in discounts %}
        <tr>
          <td>{{ discount.name }}</td>
          <td>{{ discount.description }}</td>
          <td>\[{{ discount.discount_percentage }}%\]</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No discounts created yet.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'sclad:discount_create' %}">Add Discount</a>
{% endblock %}

templates/sclad/expense_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Создание продажи</h1>
  <form method="post">
    {% csrf_token %}
    <label for="customer">Клиент:</label>
    <select name="customer" id="customer">
      {% for customer in customers %}
        <option value="{{ customer.id }}">{{ customer.name }}</option>
      {% endfor %}
    </select>
    <br>
    <label for="date">Дата:</label>
    <input type="date" name="date" id="date">
    <br>
    <label for="description">Описание:</label>
    <textarea name="description" id="description"></textarea>
    <br>
    <h2>Товары:</h2>
    {% for product in products %}
      <label for="product_{{ product.id }}">{{ product.name }} (в наличии: {{ product.quantity }})</label>
      <input type="number" name="product_{{ product.id }}" id="product_{{ product.id }}" min="0" max="{{ product.quantity }}">
      <br>
    {% endfor %}
    <button type="submit">Создать продажу</button>
  </form>
{% endblock %}

templates/sclad/expense_detail.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
       <th scope="col">Дата</th>
       <th scope="col">Покупатель</th>
       <th scope="col">% Скидка</th>
       <th scope="col">Продукт</th>
       <th scope="col">Цена</th>
       <th scope="col">Кол-во</th>
       <th scope="col">Сумма</th>
       <th scope="col">$ Скидка</th>
    </tr>
  </thead>
  <tbody>
    {% for item in expense.expensecomposition_set.all %}
    <tr>
        <td>{{ expense.date }}</td>
        <td>{{ expense.customer }}</td>
        <td>{{ expense.customer.discount }}</td>
        <td>{{ item.product.name }}</td>
        <td>${{ item.product.sell_price | floatformat:0 }}</td>
        <td>{{ item.quantity }}</td>
        <td>${{ item.total_price|floatformat:0 }}</td>
        <td>${{ item.discount_amount|floatformat:0 }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Описание</th>
        <th scope="col">Оформитель</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ expense.description }}</td>
        <td>{{ expense.user }}</td>
    </tr>
    </tbody>
</table>

{% endblock %}


<!-- discount , total_cost-->

templates/sclad/index.html
{% extends 'base.html' %}

{% block content %}
<h2 style="text-align: center">Это веб-сервис "Э-Склад" складской учет. Ver.2.0.1</h2>
<div class="container my-5" style="background-color:yellow; color:black; text-align: center;">
<h3>Описание</h3>
<p>Просто зарегистрируйся и получи доступ к сервису</p>
<p>Далее все интуитивно понятно!</p>
<p>1.Внесите все товары которые у вас уже есть на складе</p>
<p>2.Если хотите осуществить приход - сделайте приход товара</p>
<p>3.Если продаете товар - сделайте продажу товара</p>
<p>4.Вся информация о вашем складе находиться на dashborde<p>
    <p>(главная страница сервиса после вашей регистрации(LogUp) или аутентификации(LogIn) </p>
</div>
<h3>Продукт</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Артикул</th>
        <th scope="col">Название</th>
        <th scope="col">Количество</th>
        <th scope="col">Цена покупки</th>
        <th scope="col">Цена продажи</th>
        <th scope="col">Общая стоимость</th>
        <th scope="col">Общая выручка</th>
        <th scope="col">Прибыль</th>
    </tr>
    </thead>
    <tbody>
    <tr bgcolor="cuan">
        <th scope="row">-</th>
        <td>-</td>
        <td>-</td>
        <td>$</td>
        <td>$</td>
        <td>$</td>
        <td>$</td>
        <td>$</td>
    </tr>
    </tbody>
</table>
<h3>Приход товара</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Продукт</th>
        <th scope="col">Поставщик</th>
        <th scope="col">Количество</th>
        <th scope="col">Цена</th>
        <th scope="col">Сумма</th>
    </tr>
    </thead>
    <tbody>
          <tr bgcolor="cuan">
              <th scope="col">-</th>
              <th scope="col">-</th>
              <th scope="row">-</th>
              <th scope="row">$</th>
              <th scope="row">$</th>
          </tr>
    </tbody>
</table>
<h3>Продажа товара</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
       <th scope="col">Дата</th>
       <th scope="col">Покупатель</th>
       <th scope="col">% Скидка</th>
       <th scope="col">Продукт</th>
       <th scope="col">Цена</th>
       <th scope="col">Кол-во</th>
       <th scope="col">Сумма</th>
       <th scope="col">$ Скидка</th>
    </tr>
  </thead>
  <tbody>
    <tr  bgcolor="cuan">
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>$</td>
        <td>-</td>
        <td>$</td>
        <td>$</td>
    </tr>
  </tbody>
</table>


{% endblock %}

templates/sclad/product_detail.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Артикул</th>
        <th scope="col">Название</th>
        <th scope="col">Количество</th>
        <th scope="col">Цена покупки</th>
        <th scope="col">Цена продажи</th>
        <th scope="col">Общая стоимость</th>
        <th scope="col">Общая выручка</th>
        <th scope="col">Прибыль</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">{{ product.article_number }}</th>
        <td>{{ product.name }}</td>
        <td>{{ product.quantity }}</td>
        <td>${{ product.purchase_price }}</td>
        <td>${{ product.sell_price }}</td>
        <td>${{ product.balance_value }}</td>
        <td>${{ product.balance_sell }}</td>
        <td>${{ product.total_profit }}</td>
    </tr>
    </tbody>
</table>

<table class="table table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Описание</th>
        <th scope="col">Владелец</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">{{ product.description }}</th>
        <td>{{ product.user }}</td>
    </tr>
    </tbody>
</table>
{% endblock %}

templates/sclad/product_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Добавить новый продукт</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

templates/sclad/supplier_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Создание поставщика</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock %}

templates/sclad/supplier_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Suppliers</h1>
  <ul>
    {% for supplier in suppliers %}
      <li>{{ supplier.name }}</li>
    {% empty %}
      <li>No suppliers created yet.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'sclad:supplier_create' %}">Add Supplier</a>
{% endblock %}